name: Generate Snake

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: chaudharysajid007
          output: github-contribution-grid-snake.svg

      - name: Commit generated snake
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub snake"
          file_pattern: github-contribution-grid-snake.svg
